### ISSUE TITLE
Problem due to wildcard imports in JacksonAnnotationIntrospector class.

### ISSUE THREAD

**Issue by sachingorade** [codehaus/jackson#3]
JacksonAnnotationIntrospector uses JsonTypeInfo annotation from org.codehaus.jackson.annotate package to check for external properties using JsonTypeInfo.As.EXTERNAL_PROPERTY method. JacksonAnnotationIntrospector contains following import statement,

**import org.codehaus.jackson.annotate.*;**

This causes problem when some other package contains the class with same name as JsonTypeInfo such as restygwt library.

Instead of using wildcard imports, specific class name imports should be used to avoid this ind of issues.

**Comment by cowtowncoder** [comment]
I don't understand the claim -- first, Jackson 2.x `JacksonAnnotationIntrospector` definitely does not import anything from `org.codehaus.jackson.annotate` (that is Jackson 1.x package). But secondly, why should its imports have any effect to anyone outside of that class? Imports are not inherited, nor are they included in bytecode; they are only used by compiler to resolve references.

**Comment by sachingorade** [comment]
JsonTypeInfo class is in org.codehaus.jackson.annotate package. In my project I have another library [RestyGWT](https://resty-gwt.github.io/) which also contains the class with the same name as JsonTypeInfo.

Now on Tomcat 8 with Jar scanning enabled,Tomcat loads JsonTypeInfo class before JsonTypeInfo from codehaus pakcage due to which I get following exception while serialization process,

```
19-Oct-2016 14:31:11.357 SEVERE [http-apr-443-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [resteasy-servlet] in context with path [/new] threw exception [Servlet execution threw an exception] with root cause
 java.lang.NoSuchFieldError: EXTERNAL_PROPERTY
        at org.codehaus.jackson.map.introspect.JacksonAnnotationIntrospector._findTypeResolver(JacksonAnnotationIntrospector.java:781)
        at org.codehaus.jackson.map.introspect.JacksonAnnotationIntrospector.findTypeResolver(JacksonAnnotationIntrospector.java:199)
        at org.codehaus.jackson.map.AnnotationIntrospector$Pair.findTypeResolver(AnnotationIntrospector.java:1037)
        at org.codehaus.jackson.map.ser.BasicSerializerFactory.createTypeSerializer(BasicSerializerFactory.java:199)
        at org.codehaus.jackson.map.ser.BeanSerializerFactory.findPropertyContentTypeSerializer(BeanSerializerFactory.java:404)
        at org.codehaus.jackson.map.ser.BeanSerializerFactory._constructWriter(BeanSerializerFactory.java:774)
        at org.codehaus.jackson.map.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:590)
        at org.codehaus.jackson.map.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:434)
        at org.codehaus.jackson.map.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:347)
        at org.codehaus.jackson.map.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:291)
        at org.codehaus.jackson.map.ser.StdSerializerProvider._createUntypedSerializer(StdSerializerProvider.java:782)
        at org.codehaus.jackson.map.ser.StdSerializerProvider._createAndCacheUntypedSerializer(StdSerializerProvider.java:735)
        at org.codehaus.jackson.map.ser.StdSerializerProvider.findValueSerializer(StdSerializerProvider.java:344)
        at org.codehaus.jackson.map.ser.StdSerializerProvider.findTypedValueSerializer(StdSerializerProvider.java:420)
        at org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:601)
        at org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:256)
        at org.codehaus.jackson.map.ObjectMapper.writeValue(ObjectMapper.java:1613)
        at org.codehaus.jackson.jaxrs.JacksonJsonProvider.writeTo(JacksonJsonProvider.java:559)

```

Now if I remove the RestyGWT library then everything works correctly.

**Comment by sachingorade** [comment]
RestyGWT also contains JsonTypeInfo from Codehaus package,

org.codehaus.jackson.annotate.JsonTypeInfo

I think its from older version 1.7 because As enum from JsonTypeInfo, RestyGWT contains only following fields:
PROPERTY,
WRAPPER_OBJECT,
WRAPPER_ARRAY

whereas JsonTypeInfo from codehaus 1.9 package contains:
PROPERTY,
WRAPPER_OBJECT,
WRAPPER_ARRAY,
EXTERNAL_PROPERTY

So the problem is with RestyGWT packaging, instead of including classes from codehaus jar, it should have been used as dependency.

**Comment by cowtowncoder** [comment]
@sachingorade Ok thank you for explaining the problem you had. I hope the problem is or can be resolved.

**Comment by sachingorade** [comment]
@cowtowncoder Yes, problem has been resolved by removing RestyGWT jar.
